config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Question(models.Model): #질문 모델
    #글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')

    subject = models.CharField(max_length=200) #질문의 제목
    content = models.TextField() #질문의 내용
    create_date = models.DateTimeField() #질문을 작성한 일시
    modify_date = models.DateTimeField(null=True, blank=True) # 수정날짜 획인
    voter = models.ManyToManyField(User) # 추천 필드

    def __str__(self):
        return self.subject

class Answer(models.Model): #답변 모델
    # 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')

    # 어떤 질문에 대한 답변인지, 다른 모델을 속성으로 가지므로 ForeignKey, CASCADE는 질문 삭제하면 답변도 삭제되도록 함
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField() #답변의 내용
    create_date = models.DateTimeField() #답변을 작성한 일시
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User)  # 추천 필드

class Comment(models.Model):
    #질문이나 답변에 댓글이 달릴 수 있음
    #Comment 모델의 필드는, 글쓴이 내용 댓글작성일시 댓글수정일시 이댓글이달린질문 이댓글이달린답변 ...이 있다
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment

#질문 등록
class QuestionForm(forms.ModelForm): #forms.Form을 상속받으면 폼, forms.ModelForm을 상속받으면 모델 폼이라고 함
    class Meta: # 모델 폼은 필수로 Meta class를 가져야 함, 여기에는 model과 fields를 필수로 쓰기
        #QuestionForm 클래스는 Question 모델과 연결되어 있고, subject와 content를 사용한다고 정의
        model=Question
        fields=['subject', 'content']
        #form.as_p는 입력 항목을 자동으로 설정해주지만, 부트스트랩 적용이 안됨. 그럴땐 meta class에 widgets 속성을 추가
        #그런데 form.as_p는 한계가 있으므로 폼을 수작업으로 html에 작업하자

        #입력 시 subject, content를 한글로 변경하고 싶다면
        labels={
            'subject':'제목',
            'content':'내용',
        }

#답변 등록
class AnswerForm(forms.ModelForm):
    class Meta:
        model=Answer
        fields=['content']
        labels={
            'content':'답변 내용',
        }

#댓글 등록
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

pybo/views/answer_views.py
from django.contrib.auth.decorators import login_required  # 로그인해야 글 쓸 수 있게 하기
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm  # 답변 등록
from ..models import Question, Answer


@login_required(login_url='common:login') # 등록 전 로그인 되어있는지 미리 검사. 로그인 안되어있으면 로그인 화면으로 이동
def answer_create(request, question_id): # html에서 입력된 데이터가 request로 넘어옴, question_id 에서는 질문 번호 넘어옴
    #답변 등록
    question = get_object_or_404(Question, pk=question_id)
    '''
    question.answer_set.create(content=request.POST.get('content'), create_date = timezone.now())
    #request.POST.get('content') 는 request에 담긴 데이터를 추출하기 위한 것
    return redirect('pybo:detail', question_id=question.id) #redirect 함수는 전달된 값을 참고하여 페이지 이동을 함
    '''
    #form을 이용한 답변 등록, question_create와 비슷
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user # 글쓴이
            answer.create_date = timezone.now()
            answer.question=question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    #답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    #답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from ..models import Question
from django.db.models import Q, Count


def index(request):
    #목록출력
    #입력 인자
    page = request.GET.get('page','1') # 기본 페이지 = 1, get방식의 경우 url이 /?page=1
    kw = request.GET.get('kw', '') # 검색어
    so = request.GET.get('so', 'recent') #정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # 조회
    # question_list = Question.objects.order_by('-create_date')
    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    #페이징 처리
    paginator = Paginator(question_list, 10) # 페이지 당 게시글 10개씩 보여주기
    page_obj = paginator.get_page(page)

    #조회한 모델 데이터 저장
    context = {'question_list':page_obj, 'page':page, 'kw':kw}
    return render(request, 'pybo/question_list.html', context)
    #return HttpResponse("pybo에 오신 것을 환영합니다")

def detail(request, question_id):
    #목록출력
    question = get_object_or_404(Question, pk=question_id)
    #조회한 모델 데이터 저장
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib.auth.decorators import login_required  # 로그인해야 글 쓸 수 있게 하기
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib import messages

from ..forms import CommentForm  # 댓글 등록
from ..models import Question, Answer, Comment


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    #질문 댓글 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    #질문 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    #질문 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question_id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question_id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    #답변 댓글 등록
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    #답변 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    #답변 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages  # 오류 시 메세지 띄우는 용도
from django.contrib.auth.decorators import login_required  # 로그인해야 글 쓸 수 있게 하기
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm  # 질문 등록
from ..models import Question


@login_required(login_url='common:login') # 등록 전 로그인 되어있는지 미리 검사. 로그인 안되어있으면 로그인 화면으로 이동
def question_create(request):
    #질문 등록
    if request.method == 'POST': # 질문 등록 화면에서 입력 후 저장하기를 누르면 POST
        form = QuestionForm(request.POST)
        if form.is_valid(): # form이 유효한지 검사, 유효하지 않으면 오류가 저장된 것
            question = form.save(commit=False) # commit=False는, create_date를 아직 설정하지 않았으므로 임시저장 하는 것을 의미
            question.author = request.user  # 글쓴이
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else: #메소드가 GET인 경우 = 질문 등록하기 버튼을 누르면 GET
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    #질문 수정
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST": # 수정 후 저장하기 버튼 누르면 POST형식으로 호출, 데이터 수정됨
        # 조회한 question을 기본으로, 전달 받은 입력값들 덮어 써서 QuestionForm을 생성하라는 의미
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()  # 수정 일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else: # 수정 버튼을 부르면 GET방식으로 호출, 질문 수정 화면 나타남
        form = QuestionForm(instance=question) # 수정 시, 기존에 저장된 제목, 내용이 반영되어야 하기 때문에 폼 생성함
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    #질문 삭제
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    #질문 추천 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    #답글 추천 등록
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" rows="3">
            {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %} <!--base.html 상속-->
{% load pybo_filter %}
{% block content %}

<div class="container my-3"> <!--클래스 마지막의 3은 상하 마진값 3을 의미-->

    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->

            <!--기존 내용-->
            <div class="card my-3"> <!--질문, 답변은 한 뭉치이므로 부트스트랩의 card 컴포넌트 이용-->
                <div class="card-body">
                    <div class="card-text">{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end"> <!--컴포넌트 오른쪽 정렬-->

                    <!--수정 일자 표기-->
                    {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}

                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    <!--질문 수정 버튼은 글쓴이만 볼 수 있어야 함-->
                     {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                    </div>
                    {% endif %}

                    <!-- 질문 댓글 Start -->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                        <a name="comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'pybo:comment_delete_question' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 질문 댓글 End -->

                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set.count}}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <a name ="answer_{{answer.id}}"></a>

    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->

            <!-- 기존 내용-->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark }}</div>
                    <div class="d-flex justify-content-end">

                    <!--수정 일자 표기-->
                    {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}

                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                     {% if request.user == answer.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                    </div>
                    {% endif %}

                    <!--답변 댓글, 댓글 목록 보여주고 댓글 등록하는 링크 추가하기-->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name = "comment_{{comment.id}}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'pybo:comment_delete_answer' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
     <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

         <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert"> <!--에러가 나면 경고창을 띄우자-->
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

         <!-- 로그인 안하면 답변, 질문 포함 글을 작성할 수 없게 하기 -->
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

         <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert"> <!--에러가 나면 경고창을 띄우자-->
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}"> <!--오류나도 기존 입력값 유지-->
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}